import React, { useState } from 'react';
import Head from 'next/head';
import {
    Center,
    Input,
    Heading,
    Button,
    Stack,
    FormControl,
    FormLabel,
    Link,
} from '@chakra-ui/react';

import { FaGoogle } from "react-icons/fa";
import { useRouter } from 'next/router';

import { signInWithPopup, updateProfile } from 'firebase/auth';
import { auth, provider } from '@/config/firebase';
import { useAuth } from '@/context/AuthContext';


export default function Signup() {
    const { signUp, user } = useAuth();
    const router = useRouter();
    const [username, setUsername] = useState("");
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");

    const getAndSetDisplayName = () => {
        updateProfile(user!, {
            displayName: username
        });
    };

    const handleSignup = () => {
        try {
            signUp(email, password);
            getAndSetDisplayName();
        } catch (error: any) {
            console.log(error, 'could not sign user up');
            router.push('./signup');
        }
    };

    const handleGoogleSignUp = async () => {
        try {
            await signInWithPopup(auth, provider);
            router.push('./home');
        } catch (error: any) {
            console.log(error, 'could not sign user up with google');
            router.push('./signup');
        }
    };

    return (
        <>
            <Head>
                <title>Chat App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">
                <Center h={'100vh'}>
                    <form onSubmit={() => { handleSignup(); }}>
                        <Stack spacing={4} width={'lg'}>
                            <Heading size='3xl'>Sign up</Heading>
                            <Link href='/' className='text-xs'>{`Already have an account? Login`}</Link>
                            <FormControl id='displayName'>
                                <FormLabel>Username</FormLabel>
                                <Input type='text' placeholder='joseph1234' value={username} onChange={(e) => setUsername(e.target.value)} />
                            </FormControl>
                            <FormControl id='email'>
                                <FormLabel>Email address</FormLabel>
                                <Input type='email' placeholder='example@email.com' value={email} onChange={(e) => setEmail(e.target.value)} />
                            </FormControl>
                            <FormControl id='password'>
                                <FormLabel>Password</FormLabel>
                                <Input type='password' placeholder='password' value={password} onChange={(e) => setPassword(e.target.value)} />
                            </FormControl>
                            <Button type='submit' colorScheme={'blue'} size='lg'>
                                Sign in
                            </Button>
                            <Button colorScheme={'red'} size='lg' leftIcon={<FaGoogle />} onClick={() => { handleGoogleSignUp(); }}>
                                Sign up with Google
                            </Button>
                        </Stack>
                    </form>
                </Center>
            </main>
        </>
    );
}
